# Desserts {#desserts}

## Chocolate Mousse

Thomas O'Leary

### Description

Chocolate mouse is a "soft prepared food that incorporates air bubbles to give it a light and airy texture" according to (Wikipedia)[https://en.wikipedia.org/wiki/Mousse].

### Pitch

Do you like eating dessert -- but you are too nervous to bake things because you think you'll screw up the preparation, or the ingredients, or the baking time? Well, let me introduce you to my favorite dessert (and soon to be yours) chocolate mousse - _made straight from the box_! So light. So fluffy. So chocolatey. So delecious. 

Guilt-free dessert -- it's mostly air!

### Story

On my twelfth birthday, when I had learned all there is to learn, a delecious cake aflame infront of me, I said my mom -- respectfully I hope -- "What's _the big deal_ with cake? It's clearly not the best dessert. Brownies are better. Ice cream is better. Chocolate Mousse is better. People eat cake on birthdays because that is what you do, not because it is the best dessert. What's up with that?"

My mom has never let me forget that I said this -- but she has been sure to make chocolate mousse for me every major holiday since. 

### Materials

 - Box of (Chocolate Mousse Mix)[https://www.amazon.com/OETKER-Mousse-Chocolate-Milk-Ounces/dp/B00F4J7ZCI/ref=asc_df_B00F4J7ZCI/?tag=hyprod-20&linkCode=df0&hvadid=459693950627&hvpos=&hvnetw=g&hvrand=11603616910127190051&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9003006&hvtargid=pla-997270846247&psc=1]
    - Likely found in your local grocery store's pudding isle
 - Mil
 - Bowl
 - Electric mixer

### Methods

 - Add contents of the box and one cup of milk to a bowl
 - Beat with the electric mixer on low until thickened
 - Whip at the highest spead for 3 to 5 minutes
 - Spoon into serving dish
 - Chill in the refridgerator for at least an hour
 - EAT!

