# Main Dishes {#maindish}

## Yummy Butternut Squash & Pumpkin Soup

Sara Helms Cahan

### Pitch

We make this on cold snowy nights in the heart of winter - a savory and rich soup, a bit of pepper heat, elegant enough for dinner parties. Originally from Bill Neal’s Southern Cooking.

### Materials

- 1 ½ lbs fresh peeled butternut squash or pumpkin, cubed, or 1 lb canned pumpkin
- 3 Tbps butter
- ½ cup chopped scallions, white parts only
- ½ cup chopped celery
- ½ cup chopped carrots
- 1 chopped garlic clove
- 3 cups chicken or vegetable stock
- 1 cup canned Italian tomatoes, chopped, with juice
- ¼ tsp dried red pepper flakes
- ¼ tsp white pepper
- ⅛ tsp nutmeg
- 2 cups half-and-half
- Green tops of scallions, sliced thin for garnish


### Methods

1. Melt the butter in a saucepan and saute the scallions, celery and carrots gently
2. Add the garlic, stir briefly, and add the stock, tomatoes, and squash/pumpkin
3. Season with red pepper flakes, white pepper, and nutmeg
4. Cook slowly for 1 hour
5. Remove from heat, let cool slightly, and puree until texture is very smooth
6. Before serving, add half-and-half, reheat gently
7. Serve with green scallion sprinkled on top

## Uncle Moe's Latkes

Matt Futia

### Pitch

They are easy to make and can store well in the freezer if you have leftovers. 

### Story

These latkes (potato pancakes) are a favorite dish every Chanukah with my family. It's been a tradition to gather together and spend a day making batch after batch to share with family and friends. The recipe originally comes from my great Uncle Moe, who passed before I was born and who's name influenced my name -- the "M" in my first name came from his name.

### Materials

- 8 medium potatoes peeled  and placed in water
- 1 lg onion, peeled and finely grated
- 2 eggs
- 1 tsp. salt
- ½ tsp. pepper
- 1 tbsp. baking powder
- 1 cup matzo meal or bread crumbs         
- vegetable oil


### Methods

1. Grate potatoes with food processor
2. Mix with grated onion, add eggs, salt, pepper and baking powder
3. Pour into large bowl, add matzo meal and mix thoroughly
4. Heat oil, and drop mixture into frying pan
5. Turn when crisp and drain on brown paper bags
6. Serve alone or with apple sauce


## Mashed Sweet Potatoes with Pecan Streusel

Kristin Bishop

### Pitch

I have been making this for friends and family for nearly 20 years and in all that time I don't think I have ever not had anyone ask me for the recipe. This one is a BIG winner.

### Materials

- 10 meduim-sized tan-skinned sweet potatoes (~6 lbs), scrubbed  (I go by weight)
- 4 bananas, unpeeled
- 1 cup butter, room temperature
- ⅓ cup honey
- I added some cinnamon and ground cloves
- 1 ½ cups pecan pieces
- ¾ cup packed golden brown sugar
- ½ cup all purpose flour

- makes about 12 servings

### Methods

1. Preheat oven to 400ºF.  
2. Pierce sweet potatoes with fork.  
3. Place on rimmed baking sheet or in roasting pan and bake until almost soft, about 40 minutes (I find that this usually takes closer to 60, but it depends on the size of the sweet potatoes)  
4. Add bananas to roasting pan alongside sweet potatoes and bake until banana skins brown, about 10 minutes 
5. Let sweet potatoes and bananas stand at room temperature until cool enough to handle, about 15 minutes (maintain oven temperature)
6. Cut sweet potatoes in half
7. Scoop flesh from sweet potatoes into large bowl
8. Peel bananas; add to bowl
9. Add ½ cup butter and honey 
10. Beat with wooden spoon until blended and fluffy
11. Season to taste with salt
12. Transfer to 8-10 cup ovenproof baking dish
13. Mix nuts, sugar and flour in bowl
14. Add ½ cup butter, mix with fingertips until coarse crumbs form (Potatoes and streusel can be made one day ahead)
15. Cover separately; chill.
16. Before continuing, preheat oven to 400ºF.  
17. Sprinkle streusel over potatoes.  
18. Bake until top is golden brown and potatoes are hot, about 25 minutes.
