--- 
title: "Biology Holiday Cookbook!"
author: "University of Vermont\nBiology Department"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
site: bookdown::bookdown_site
output: bookdown::gitbook
output_dir: "docs"
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: tsoleary/bio_cookbookdown
description: "This cookbook is a compilation of The University of Vermont Biology Department's favorite holiday recipes - a way to virutally spread tasty holiday cheer!"
---

# Introduction

## Our mission

This cookbook is a compilation of The University of Vermont Biology Department's favorite holiday recipes.

One of the best parts of the holiday season is often sitting around a table, enjoying food together, and sharing the personal stories that are behind each recipe. This year we can’t come together in person, but we can still share those stories, and hopefully spread some holiday cheer in the form of _good food_! 

We hope this cookbook is an opportunity for us to get to know each other a little better. It is a place where we can share the meaningful stories behind our favorite recipes, and try delicious new recipes.

You may submit new recipes on [this google form](https://docs.google.com/forms/d/e/1FAIpQLSdHOm3Liu3LtlvbZvr9YFWXiYRM_SHFl1M4b22EPs0DGhbhYw/viewform?usp=sf_link).

## Contact us

Please reach out to us! Send all correspondance to the Biology Social Committee (<a href="uvmbiopartyplanning@gmail.com">)!

- Send us more about your favorite recipe and add to your story
- Send us pictures of meals you've prepared.
- Send us reviews of recipes you've tried.
- Send us any other comments, suggestions, or corrections 


```{r, eval = FALSE, include = FALSE}
# How to build the book when changes are made
require(bookdown)
render_book(input = ".", output_format = NULL,
   clean = TRUE, envir = parent.frame(), 
   output_dir = "docs",
   new_session = NA, preview = TRUE,
   config_file = "_bookdown.yml")
```

